<?php
require_once 'auth.php';
require_once 'db_connect.php';
requireAdmin();

$user = currentUser();
$tab  = $_GET['tab'] ?? 'users';
$msg  = '';
$msgType = 'success';

// ── Branding config writer helper ─────────────────────────────
function writeBrandingConfig(string $logo, string $navBg, string $navBorder,
                             string $accent, string $navText,
                             string $siteName, string $mailFrom, string $mailName): bool {
    $f  = __DIR__ . '/branding_config.php';
    $c  = "<?php\n// Auto-generated by Admin Panel\n";
    $c .= "define('BRAND_LOGO',       " . var_export($logo,      true) . ");\n";
    $c .= "define('BRAND_NAV_BG',     " . var_export($navBg,     true) . ");\n";
    $c .= "define('BRAND_NAV_BORDER', " . var_export($navBorder, true) . ");\n";
    $c .= "define('BRAND_ACCENT',     " . var_export($accent,    true) . ");\n";
    $c .= "define('BRAND_TEXT',       " . var_export($navText,   true) . ");\n";
    $c .= "define('SITE_NAME',        " . var_export($siteName,  true) . ");\n";
    $c .= "define('MAIL_FROM',        " . var_export($mailFrom,  true) . ");\n";
    $c .= "define('MAIL_FROM_NAME',   " . var_export($mailName,  true) . ");\n";
    return file_put_contents($f, $c) !== false;
}

// ── Read current branding values ──────────────────────────────
$_bcf = __DIR__ . '/branding_config.php';
if (file_exists($_bcf) && !defined('BRAND_LOGO')) { require_once $_bcf; }
$curLogo    = defined('BRAND_LOGO')       ? BRAND_LOGO       : '';
$curNavBg   = defined('BRAND_NAV_BG')     ? BRAND_NAV_BG     : '#1a252f';
$curBorder  = defined('BRAND_NAV_BORDER') ? BRAND_NAV_BORDER : '#0d1b24';
$curAccent  = defined('BRAND_ACCENT')     ? BRAND_ACCENT     : '#3498db';
$curText    = defined('BRAND_TEXT')       ? BRAND_TEXT       : '#ffffff';
$curSite    = defined('SITE_NAME')        ? SITE_NAME        : 'Store Display System';
$curMail    = defined('MAIL_FROM')        ? MAIL_FROM        : 'noreply@yourdomain.com';
$curMailN   = defined('MAIL_FROM_NAME')   ? MAIL_FROM_NAME   : 'Display System';

// ============================================================
// USER MANAGEMENT ACTIONS
// ============================================================
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verifyCsrf();

    // Create user
    if (isset($_POST['action_create_user'])) {
        $uname = trim($_POST['username'] ?? '');
        $email = trim($_POST['email']    ?? '');
        $pass  = $_POST['password']      ?? '';
        $role  = in_array($_POST['role'] ?? '', ['admin','basic']) ? $_POST['role'] : 'basic';

        if (!$uname || !$email || !$pass) {
            $msg = 'All fields are required.'; $msgType = 'error';
        } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $msg = 'Invalid email address.'; $msgType = 'error';
        } elseif (strlen($pass) < 8) {
            $msg = 'Password must be at least 8 characters.'; $msgType = 'error';
        } else {
            try {
                $pdo->prepare("INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, ?)")
                    ->execute([$uname, $email, password_hash($pass, PASSWORD_DEFAULT), $role]);
                $msg = "User \"$uname\" created.";
            } catch (PDOException $e) {
                $msg = 'Username or email already exists.'; $msgType = 'error';
            }
        }
        $tab = 'users';
    }

    // Edit user (role, active status)
    if (isset($_POST['action_edit_user'])) {
        $uid    = intval($_POST['edit_id'] ?? 0);
        $role   = in_array($_POST['edit_role'] ?? '', ['admin','basic']) ? $_POST['edit_role'] : 'basic';
        $active = isset($_POST['edit_active']) ? 1 : 0;
        $email  = trim($_POST['edit_email'] ?? '');
        if ($uid === $user['id'] && $role !== 'admin') {
            $msg = 'You cannot demote your own account.'; $msgType = 'error';
        } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $msg = 'Invalid email address.'; $msgType = 'error';
        } else {
            $pdo->prepare("UPDATE users SET role = ?, is_active = ?, email = ? WHERE id = ?")
                ->execute([$role, $active, $email, $uid]);
            $msg = 'User updated.';
        }
        $tab = 'users';
    }

    // Reset another user's password
    if (isset($_POST['action_reset_pass'])) {
        $uid  = intval($_POST['reset_uid'] ?? 0);
        $pass = $_POST['new_pass'] ?? '';
        if (strlen($pass) < 8) {
            $msg = 'Password must be at least 8 characters.'; $msgType = 'error';
        } else {
            $pdo->prepare("UPDATE users SET password_hash = ? WHERE id = ?")
                ->execute([password_hash($pass, PASSWORD_DEFAULT), $uid]);
            $msg = 'Password reset.';
        }
        $tab = 'users';
    }

    // Delete user
    if (isset($_POST['action_delete_user'])) {
        $uid = intval($_POST['del_id'] ?? 0);
        if ($uid === $user['id']) {
            $msg = 'You cannot delete your own account.'; $msgType = 'error';
        } else {
            $pdo->prepare("DELETE FROM users WHERE id = ?")->execute([$uid]);
            $msg = 'User deleted.';
        }
        $tab = 'users';
    }

    // Save branding (logo + colors)
    if (isset($_POST['action_save_branding'])) {
        $navBg     = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_bg']     ?? '') ? $_POST['nav_bg']     : $curNavBg;
        $navBorder = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_border'] ?? '') ? $_POST['nav_border'] : $curBorder;
        $accent    = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['accent']     ?? '') ? $_POST['accent']     : $curAccent;
        $navText   = preg_match('/^#[0-9a-fA-F]{6}$/', $_POST['nav_text']   ?? '') ? $_POST['nav_text']   : $curText;
        $rawExist  = $_POST['existing_logo'] ?? '';
        $logoPath  = preg_match('/^uploads\/brand_logo\.[a-z]{2,4}$/', $rawExist) ? $rawExist : $curLogo;
        if (!empty($_FILES['logo_file']['name'])) {
            $allowed = ['image/png'=>'png','image/jpeg'=>'jpg','image/gif'=>'gif',
                        'image/webp'=>'webp','image/svg+xml'=>'svg'];
            $mime = mime_content_type($_FILES['logo_file']['tmp_name']);
            if (!isset($allowed[$mime])) {
                $msg = 'Logo must be PNG, JPG, GIF, WEBP, or SVG.'; $msgType = 'error';
            } else {
                $dest = __DIR__ . '/uploads/brand_logo.' . $allowed[$mime];
                if (!move_uploaded_file($_FILES['logo_file']['tmp_name'], $dest)) {
                    $msg = 'Could not save logo. Check uploads/ folder permissions.'; $msgType = 'error';
                } else {
                    $logoPath = 'uploads/brand_logo.' . $allowed[$mime];
                }
            }
        }
        if ($msg === '') {
            if (writeBrandingConfig($logoPath, $navBg, $navBorder, $accent, $navText, $curSite, $curMail, $curMailN)) {
                $curLogo = $logoPath; $curNavBg = $navBg; $curBorder = $navBorder; $curAccent = $accent; $curText = $navText;
                $msg = 'Branding saved.';
            } else {
                $msg = 'Could not write branding_config.php. Check file permissions.'; $msgType = 'error';
            }
        }
        $tab = 'branding';
    }

    // Save site & email settings
    if (isset($_POST['action_save_settings'])) {
        $siteName = trim($_POST['site_name'] ?? '') ?: $curSite;
        $mailFrom = filter_var(trim($_POST['mail_from'] ?? ''), FILTER_VALIDATE_EMAIL) ?: $curMail;
        $mailName = trim($_POST['mail_name'] ?? '') ?: $curMailN;
        if (writeBrandingConfig($curLogo, $curNavBg, $curBorder, $curAccent, $curText, $siteName, $mailFrom, $mailName)) {
            $curSite = $siteName; $curMail = $mailFrom; $curMailN = $mailName;
            $msg = 'Settings saved.';
        } else {
            $msg = 'Could not write branding_config.php. Check file permissions.'; $msgType = 'error';
        }
        $tab = 'settings';
    }

    // Save brand standards
    if (isset($_POST['action_save_styles'])) {
        $types = ['section_header','item_title','item_title_2','price','price_2','description'];
        $stmt  = $pdo->prepare(
            "UPDATE block_styles SET font_family=?, font_size=?, font_color=?, font_weight=?, font_style=?, line_height=? WHERE block_type=?"
        );
        foreach ($types as $t) {
            $stmt->execute([
                $_POST["bs_{$t}_family"]      ?? 'Arial',
                intval($_POST["bs_{$t}_size"] ?? 16),
                $_POST["bs_{$t}_color"]       ?? '#000000',
                $_POST["bs_{$t}_weight"]      ?? 'normal',
                $_POST["bs_{$t}_fstyle"]      ?? 'normal',
                number_format(floatval($_POST["bs_{$t}_lh"] ?? 1.4), 2),
                $t,
            ]);
        }
        $msg = 'Brand standards saved.';
        $tab = 'brand';
    }
}

// ---- READ DATA ----
$users  = $pdo->query("SELECT * FROM users ORDER BY role DESC, username ASC")->fetchAll();
$styles = [];
foreach ($pdo->query("SELECT * FROM block_styles")->fetchAll() as $s) {
    $styles[$s['block_type']] = $s;
}
$typeLabels = [
    'section_header' => 'Section Header',
    'item_title'     => 'Item Title',
    'item_title_2'   => 'Item Title 2',
    'price'          => 'Price',
    'price_2'        => 'Price 2',
    'description'    => 'Description',
];
$fontFamilies = ['Arial','Georgia','Verdana','Tahoma','Trebuchet MS','Times New Roman','Courier New','Impact'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Panel — <?= htmlspecialchars(SITE_NAME) ?></title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
        body { background: #f0f2f5; min-height: 100vh; }

        /* --- Nav --- */
        nav { background: #1a252f; padding: 0 20px; display: flex; align-items: center; gap: 20px; height: 52px; }
        nav .brand { color: #fff; font-weight: bold; font-size: 15px; margin-right: auto; }
        nav a { color: #bdc3c7; text-decoration: none; font-size: 13px; padding: 6px 10px; border-radius: 4px; }
        nav a:hover, nav a.active { background: #2c3e50; color: #fff; }
        nav .role-badge { background: #e74c3c; color: #fff; font-size: 11px; font-weight: bold;
                          padding: 2px 8px; border-radius: 10px; }

        /* --- Tabs --- */
        .tabs { display: flex; gap: 2px; background: #dde3ea; padding: 6px 24px 0; }
        .tab-btn { padding: 9px 20px; border: none; cursor: pointer; font-size: 14px; font-weight: 600;
                   background: transparent; color: #555; border-radius: 6px 6px 0 0; }
        .tab-btn.active { background: #fff; color: #2c3e50; }

        /* --- Content --- */
        .content { padding: 24px; max-width: 1100px; margin: 0 auto; }
        .msg-box { padding: 11px 16px; border-radius: 5px; margin-bottom: 18px; font-size: 14px; }
        .msg-success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .msg-error   { background: #fdecea; color: #c0392b; border: 1px solid #e74c3c; }

        /* --- Cards --- */
        .card { background: #fff; border-radius: 8px; padding: 22px; box-shadow: 0 2px 8px rgba(0,0,0,.07); margin-bottom: 20px; }
        .card h2 { font-size: 16px; color: #2c3e50; margin-bottom: 16px; border-bottom: 1px solid #eee; padding-bottom: 10px; }

        /* --- Forms --- */
        .form-row { display: flex; gap: 12px; flex-wrap: wrap; align-items: flex-end; margin-bottom: 12px; }
        .form-group { display: flex; flex-direction: column; gap: 4px; }
        .form-group label { font-size: 12px; font-weight: 600; color: #666; }
        input[type="text"], input[type="email"], input[type="password"],
        input[type="number"], select {
            padding: 8px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 14px;
        }
        input[type="color"] { padding: 2px; height: 34px; cursor: pointer; border: 1px solid #ccc; border-radius: 4px; }
        .btn { padding: 8px 16px; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; font-size: 13px; }
        .btn-blue   { background: #3498db; color: #fff; }
        .btn-blue:hover   { background: #2980b9; }
        .btn-green  { background: #27ae60; color: #fff; }
        .btn-green:hover  { background: #219a52; }
        .btn-red    { background: #e74c3c; color: #fff; }
        .btn-red:hover    { background: #c0392b; }
        .btn-gray   { background: #95a5a6; color: #fff; }

        /* --- User table --- */
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #ecf0f1; }
        th { background: #f8f9fa; font-weight: 600; color: #555; }
        tr:hover td { background: #fafbfc; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: bold; }
        .badge-admin { background: #e8d5fb; color: #6c3483; }
        .badge-basic { background: #d6eaf8; color: #1a5276; }
        .badge-active   { background: #d4efdf; color: #1e8449; }
        .badge-inactive { background: #fdecea; color: #c0392b; }

        /* --- Edit row --- */
        .edit-row { display: none; background: #f8f9fa; }
        .edit-row.open { display: table-row; }
        .edit-row td { padding: 12px; }

        /* --- Brand standards --- */
        .bs-table { width: 100%; border-collapse: collapse; }
        .bs-table th, .bs-table td { padding: 10px 8px; border-bottom: 1px solid #eee; font-size: 13px; }
        .bs-table th { background: #f8f9fa; font-weight: 600; color: #555; }
        .bs-table input[type="number"] { width: 70px; }
        .bs-table select { min-width: 130px; }
        .preview-text { padding: 4px 8px; border: 1px solid #eee; border-radius: 3px; white-space: nowrap; }

        /* --- Work Area element type badges --- */
        .el-badge { display:inline-block; padding:2px 7px; border-radius:3px; font-size:11px; font-weight:bold; text-transform:uppercase; }
        .el-section  { background:#e8d5fb; color:#6c3483; }
        .el-text      { background:#d6eaf8; color:#1a5276; }
        .el-image     { background:#d4efdf; color:#1e8449; }
        .el-video     { background:#fde8d8; color:#a04000; }
        .el-carousel  { background:#fef9e7; color:#7d6608; border:1px solid #d4ac0d; }
        .el-table     { background:#eaf7fb; color:#0e6655; }
        .el-marquee   { background:#fdedec; color:#922b21; }
        .el-desc { font-size:13px; color:#2c3e50; max-width:320px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
        .el-hidden-tag { display:inline-block; padding:1px 6px; border-radius:8px; font-size:10px;
                         font-weight:bold; background:#fdecea; color:#c0392b; margin-left:6px; vertical-align:middle; }
    </style>
</head>
<body>

<nav>
    <span class="brand"><?= htmlspecialchars(SITE_NAME) ?></span>
    <a href="builder.php">Builder</a>
    <a href="crud.php">Asset Manager</a>
    <a href="admin_panel.php" class="active">Admin Panel</a>
    <span style="color:#bdc3c7; font-size:13px;">
        <?= htmlspecialchars($user['username']) ?>
        <span class="role-badge">ADMIN</span>
    </span>
    <a href="logout.php">Sign Out</a>
</nav>

<div class="tabs">
    <button class="tab-btn <?= $tab==='users'    ?'active':'' ?>" onclick="showTab('users')">User Management</button>
    <button class="tab-btn <?= $tab==='brand'    ?'active':'' ?>" onclick="showTab('brand')">Display Branding</button>
    <button class="tab-btn <?= $tab==='branding' ?'active':'' ?>" onclick="showTab('branding')">Site Branding</button>
    <button class="tab-btn <?= $tab==='settings' ?'active':'' ?>" onclick="showTab('settings')">Settings</button>
    <button class="tab-btn <?= $tab==='workarea' ?'active':'' ?>" onclick="showTab('workarea')">Work Area</button>
</div>

<div class="content">

<?php if ($msg): ?>
    <div class="msg-box msg-<?= $msgType ?>"><?= htmlspecialchars($msg) ?></div>
<?php endif; ?>

<!-- ============================================================ -->
<!-- USERS TAB                                                     -->
<!-- ============================================================ -->
<div id="tab-users" style="display:<?= $tab==='users'?'block':'none' ?>">
    <div class="card">
        <h2>Add New User</h2>
        <form method="POST">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
            <div class="form-row">
                <div class="form-group">
                    <label>Username</label>
                    <input type="text" name="username" placeholder="janedoe" required style="width:150px;">
                </div>
                <div class="form-group">
                    <label>Email Address</label>
                    <input type="email" name="email" placeholder="jane@store.com" required style="width:200px;">
                </div>
                <div class="form-group">
                    <label>Temp Password</label>
                    <input type="password" name="password" placeholder="min 8 chars" required style="width:160px;">
                </div>
                <div class="form-group">
                    <label>Role</label>
                    <select name="role" style="width:100px;">
                        <option value="basic">Basic User</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>&nbsp;</label>
                    <button type="submit" name="action_create_user" class="btn btn-green">Add User</button>
                </div>
            </div>
        </form>
    </div>

    <div class="card">
        <h2>All Users (<?= count($users) ?>)</h2>
        <table>
            <thead>
                <tr>
                    <th>Username</th><th>Email</th><th>Role</th>
                    <th>Status</th><th>Created</th><th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $u): ?>
                <tr>
                    <td><strong><?= htmlspecialchars($u['username']) ?></strong>
                        <?php if ($u['id'] === $user['id']): ?>
                            <span style="font-size:11px; color:#7f8c8d;">(you)</span>
                        <?php endif; ?>
                    </td>
                    <td><?= htmlspecialchars($u['email']) ?></td>
                    <td><span class="badge badge-<?= $u['role'] ?>"><?= strtoupper($u['role']) ?></span></td>
                    <td><span class="badge badge-<?= $u['is_active']?'active':'inactive' ?>">
                        <?= $u['is_active'] ? 'Active' : 'Inactive' ?>
                    </span></td>
                    <td><?= date('M j, Y', strtotime($u['created_at'])) ?></td>
                    <td>
                        <button class="btn btn-blue" style="font-size:11px; padding:5px 10px;"
                                onclick="toggleEdit(<?= $u['id'] ?>)">Edit</button>

                        <?php if ($u['id'] !== $user['id']): ?>
                        <form method="POST" style="display:inline;"
                              onsubmit="return confirm('Delete user <?= htmlspecialchars($u['username']) ?>?')">
                            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
                            <input type="hidden" name="del_id" value="<?= $u['id'] ?>">
                            <button type="submit" name="action_delete_user"
                                    class="btn btn-red" style="font-size:11px; padding:5px 10px;">Delete</button>
                        </form>
                        <?php endif; ?>
                    </td>
                </tr>
                <!-- Inline edit row -->
                <tr class="edit-row" id="edit-<?= $u['id'] ?>">
                    <td colspan="6">
                        <form method="POST">
                            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
                            <div class="form-row">
                                <input type="hidden" name="edit_id" value="<?= $u['id'] ?>">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" name="edit_email"
                                           value="<?= htmlspecialchars($u['email']) ?>" style="width:200px;" required>
                                </div>
                                <div class="form-group">
                                    <label>Role</label>
                                    <select name="edit_role" style="width:100px;">
                                        <option value="basic"  <?= $u['role']==='basic' ?'selected':'' ?>>Basic</option>
                                        <option value="admin"  <?= $u['role']==='admin' ?'selected':'' ?>>Admin</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>
                                        <input type="checkbox" name="edit_active" value="1"
                                               <?= $u['is_active']?'checked':'' ?>> Active
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label>&nbsp;</label>
                                    <button type="submit" name="action_edit_user"
                                            class="btn btn-green" style="font-size:12px;">Save</button>
                                </div>
                            </div>
                        </form>
                        <form method="POST" style="margin-top:8px;">
                            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
                            <div class="form-row">
                                <input type="hidden" name="reset_uid" value="<?= $u['id'] ?>">
                                <div class="form-group">
                                    <label>Set New Password</label>
                                    <input type="password" name="new_pass" placeholder="min 8 characters" style="width:200px;">
                                </div>
                                <div class="form-group">
                                    <label>&nbsp;</label>
                                    <button type="submit" name="action_reset_pass"
                                            class="btn btn-gray" style="font-size:12px;">Reset Password</button>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- ============================================================ -->
<!-- BRAND STANDARDS TAB                                          -->
<!-- ============================================================ -->
<div id="tab-brand" style="display:<?= $tab==='brand'?'block':'none' ?>">
    <div class="card">
        <h2>Brand Standards — Locked Text Styles</h2>
        <p style="font-size:13px; color:#7f8c8d; margin-bottom:16px;">
            These styles apply to the four typed text blocks. Basic users cannot change them.
            Changes take effect immediately on the display screen.
        </p>
        <form method="POST">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
            <table class="bs-table">
                <thead>
                    <tr>
                        <th>Block Type</th>
                        <th>Font Family</th>
                        <th>Size (px)</th>
                        <th>Color</th>
                        <th>Weight</th>
                        <th>Style</th>
                        <th>Line Height</th>
                        <th>Live Preview</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($typeLabels as $t => $label):
                    $s = $styles[$t] ?? [];
                    $ff = $s['font_family'] ?? 'Arial';
                    $fs = $s['font_size']   ?? 16;
                    $fc = $s['font_color']  ?? '#000000';
                    $fw = $s['font_weight'] ?? 'normal';
                    $fi = $s['font_style']  ?? 'normal';
                    $lh = $s['line_height'] ?? 1.4;
                ?>
                <tr id="bs-row-<?= $t ?>">
                    <td><strong><?= htmlspecialchars($label) ?></strong></td>
                    <td>
                        <select name="bs_<?= $t ?>_family" onchange="updatePreview('<?= $t ?>')">
                            <?php foreach ($fontFamilies as $ff_opt): ?>
                                <option value="<?= htmlspecialchars($ff_opt) ?>"
                                    <?= $ff === $ff_opt ? 'selected' : '' ?>><?= $ff_opt ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="bs_<?= $t ?>_size" value="<?= intval($fs) ?>"
                               min="8" max="200" onchange="updatePreview('<?= $t ?>')">
                    </td>
                    <td>
                        <input type="color" name="bs_<?= $t ?>_color" value="<?= htmlspecialchars($fc) ?>"
                               oninput="updatePreview('<?= $t ?>')">
                    </td>
                    <td>
                        <select name="bs_<?= $t ?>_weight" onchange="updatePreview('<?= $t ?>')">
                            <option value="normal" <?= $fw==='normal'?'selected':'' ?>>Normal</option>
                            <option value="bold"   <?= $fw==='bold'  ?'selected':'' ?>>Bold</option>
                        </select>
                    </td>
                    <td>
                        <select name="bs_<?= $t ?>_fstyle" onchange="updatePreview('<?= $t ?>')">
                            <option value="normal" <?= $fi==='normal' ?'selected':'' ?>>Normal</option>
                            <option value="italic" <?= $fi==='italic' ?'selected':'' ?>>Italic</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" name="bs_<?= $t ?>_lh" value="<?= number_format(floatval($lh),2) ?>"
                               min="0.8" max="4" step="0.1" style="width:70px;" onchange="updatePreview('<?= $t ?>')">
                    </td>
                    <td style="max-width:220px; overflow:hidden; white-space:nowrap;">
                        <span class="preview-text" id="preview-<?= $t ?>"
                              style="font-family:<?= htmlspecialchars($ff) ?>; font-size:<?= intval($fs) ?>px;
                                     color:<?= htmlspecialchars($fc) ?>; font-weight:<?= htmlspecialchars($fw) ?>;
                                     font-style:<?= htmlspecialchars($fi) ?>; line-height:<?= floatval($lh) ?>;
                                     display:inline-block; max-width:200px; overflow:hidden; white-space:nowrap; vertical-align:middle;">
                            <?= htmlspecialchars($label) ?>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div style="margin-top:16px;">
                <button type="submit" name="action_save_styles" class="btn btn-green">
                    Save Brand Standards
                </button>
            </div>
        </form>
    </div>
</div>

<!-- ============================================================ -->
<!-- BRANDING TAB                                                  -->
<!-- ============================================================ -->
<div id="tab-branding" style="display:<?= $tab==='branding'?'block':'none' ?>">
    <form method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">
        <input type="hidden" name="existing_logo" value="<?= htmlspecialchars($curLogo) ?>">

        <div class="card">
            <h2>Logo</h2>
            <?php if ($curLogo): ?>
                <div style="margin-bottom:10px;">
                    <img src="<?= htmlspecialchars($curLogo) ?>" alt="Current logo"
                         style="max-height:60px; max-width:200px; object-fit:contain; border:1px solid #eee; padding:4px; border-radius:4px;">
                </div>
                <p style="font-size:12px; color:#7f8c8d; margin-bottom:10px;">Current: <?= htmlspecialchars($curLogo) ?></p>
            <?php endif; ?>
            <div class="form-group">
                <label>Upload Logo (PNG, JPG, SVG)</label>
                <input type="file" name="logo_file" accept="image/*" onchange="previewBrandLogo(this)">
            </div>
            <p style="font-size:12px; color:#7f8c8d; margin-top:6px;">Max 2 MB. Leave blank to keep existing logo.</p>
            <div id="brand-logo-preview" style="margin-top:10px;display:none;">
                <img id="brand-logo-img" src="" alt="" style="max-height:60px; max-width:200px; object-fit:contain;">
            </div>
        </div>

        <div class="card">
            <h2>Nav Colors</h2>
            <table style="border-collapse:collapse; width:100%; font-size:13px;">
                <tr>
                    <td style="padding:8px 0; width:160px; color:#555; font-weight:600;">Nav Background</td>
                    <td style="padding:8px 0;"><input type="color" name="nav_bg" value="<?= htmlspecialchars($curNavBg) ?>" oninput="brandPreview()"></td>
                    <td style="padding:8px 12px; color:#7f8c8d; font-size:12px;">Top navigation background</td>
                </tr>
                <tr>
                    <td style="padding:8px 0; color:#555; font-weight:600;">Nav Border</td>
                    <td style="padding:8px 0;"><input type="color" name="nav_border" value="<?= htmlspecialchars($curBorder) ?>" oninput="brandPreview()"></td>
                    <td style="padding:8px 12px; color:#7f8c8d; font-size:12px;">Bottom border line on nav</td>
                </tr>
                <tr>
                    <td style="padding:8px 0; color:#555; font-weight:600;">Accent Color</td>
                    <td style="padding:8px 0;"><input type="color" name="accent" value="<?= htmlspecialchars($curAccent) ?>" oninput="brandPreview()"></td>
                    <td style="padding:8px 12px; color:#7f8c8d; font-size:12px;">Buttons and highlights</td>
                </tr>
                <tr>
                    <td style="padding:8px 0; color:#555; font-weight:600;">Nav Text Color</td>
                    <td style="padding:8px 0;"><input type="color" name="nav_text" value="<?= htmlspecialchars($curText) ?>" oninput="brandPreview()"></td>
                    <td style="padding:8px 12px; color:#7f8c8d; font-size:12px;">Site name text in the nav</td>
                </tr>
            </table>

            <div style="margin-top:16px; background:#2c3e50; border-radius:6px; padding:10px 14px;
                        display:flex; align-items:center; gap:14px;" id="brand-preview-nav">
                <span id="bpv-brand" style="font-weight:bold; font-size:14px; color:<?= htmlspecialchars($curText) ?>;">
                    <?= htmlspecialchars($curSite) ?>
                </span>
                <span id="bpv-btn" style="background:<?= htmlspecialchars($curAccent) ?>; color:#fff;
                      padding:4px 12px; border-radius:4px; font-size:12px;">Publish</span>
            </div>
        </div>

        <button type="submit" name="action_save_branding" class="btn btn-green">Save Branding</button>
    </form>
</div>

<!-- ============================================================ -->
<!-- SETTINGS TAB                                                  -->
<!-- ============================================================ -->
<div id="tab-settings" style="display:<?= $tab==='settings'?'block':'none' ?>">
    <form method="POST">
        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrfToken()) ?>">

        <div class="card">
            <h2>Site Name</h2>
            <div class="form-group" style="max-width:400px;">
                <label>Site Name</label>
                <input type="text" name="site_name" value="<?= htmlspecialchars($curSite) ?>"
                       placeholder="Store Display System" style="width:100%;">
            </div>
            <p style="font-size:12px; color:#7f8c8d; margin-top:6px;">Shown in browser tab and on the login screen.</p>
        </div>

        <div class="card">
            <h2>Email Settings</h2>
            <p style="font-size:13px; color:#7f8c8d; margin-bottom:14px;">
                Used for password-reset emails. The <em>From Address</em> must be a real mailbox on your
                hosting domain (e.g. <code>noreply@biggbrawler.com</code>) for emails to be delivered.
            </p>
            <div class="form-row">
                <div class="form-group" style="flex:1; min-width:220px;">
                    <label>From Address</label>
                    <input type="email" name="mail_from" value="<?= htmlspecialchars($curMail) ?>"
                           placeholder="noreply@yourdomain.com" style="width:100%;">
                </div>
                <div class="form-group" style="flex:1; min-width:200px;">
                    <label>From Name</label>
                    <input type="text" name="mail_name" value="<?= htmlspecialchars($curMailN) ?>"
                           placeholder="Display System" style="width:100%;">
                </div>
            </div>
        </div>

        <button type="submit" name="action_save_settings" class="btn btn-green">Save Settings</button>
    </form>
</div>

<!-- ============================================================ -->
<!-- WORK AREA TAB                                                  -->
<!-- ============================================================ -->
<div id="tab-workarea" style="display:<?= $tab==='workarea'?'block':'none' ?>">
    <div class="card">
        <h2>Canvas Elements</h2>
        <p style="font-size:13px; color:#7f8c8d; margin-bottom:16px;">
            All elements currently on the builder canvas. Hide removes the element from the viewer display immediately — no publish required. Delete permanently removes it from the canvas.
        </p>
        <div style="margin-bottom:14px;">
            <button class="btn btn-blue" style="font-size:12px;" onclick="loadCanvasElements()">&#8635; Refresh</button>
        </div>
        <div id="canvas-elements-wrap">
            <p style="color:#7f8c8d;font-size:13px;">Click Refresh or open this tab to load.</p>
        </div>
    </div>
</div>

</div><!-- .content -->

<script>
    var _tabs = ['users','brand','branding','settings','workarea'];
    function showTab(name) {
        _tabs.forEach(function(t) {
            document.getElementById('tab-' + t).style.display = t === name ? 'block' : 'none';
        });
        document.querySelectorAll('.tab-btn').forEach(function(b, i) {
            b.classList.toggle('active', _tabs[i] === name);
        });
        if (name === 'workarea') loadCanvasElements();
    }

    // ── Work Area ──────────────────────────────────────────────
    function loadCanvasElements() {
        var wrap = document.getElementById('canvas-elements-wrap');
        wrap.innerHTML = '<p style="color:#7f8c8d;font-size:13px;">Loading…</p>';
        fetch('api.php?action=get_canvas_elements')
            .then(function(r) { return r.json(); })
            .then(function(data) {
                if (!Array.isArray(data) || !data.length) {
                    wrap.innerHTML = '<p style="color:#7f8c8d;font-size:13px;">No elements on the canvas.</p>';
                    return;
                }
                renderElementsList(data);
            })
            .catch(function() {
                wrap.innerHTML = '<p style="color:#e74c3c;font-size:13px;">Failed to load elements.</p>';
            });
    }

    function renderElementsList(elements) {
        // Map section id → display number
        var secNum = {}, n = 0;
        elements.forEach(function(el) { if (el.type === 'section') secNum[el.id] = ++n; });

        var rows = elements.map(function(el) {
            var isHidden = parseInt(el.hidden) === 1;
            var parentCell = el.section_id
                ? '<span style="font-size:11px;color:#7f8c8d;">Section ' + (secNum[el.section_id] || el.section_id) + '</span>'
                : '—';
            var hiddenTag  = isHidden ? '<span class="el-hidden-tag">HIDDEN</span>' : '';
            var toggleLbl  = isHidden ? '&#128065; Show' : '&#128683; Hide';
            var toggleCls  = isHidden ? 'btn-green' : 'btn-gray';
            return '<tr>' +
                '<td><span class="el-badge el-' + el.type + '">' + el.type + '</span></td>' +
                '<td><span class="el-desc">' + escHtml(elDesc(el)) + '</span>' + hiddenTag + '</td>' +
                '<td>' + parentCell + '</td>' +
                '<td style="white-space:nowrap;color:#555;">' + el.width + '×' + el.height + '</td>' +
                '<td><button class="btn ' + toggleCls + '" style="font-size:11px;padding:4px 10px;" ' +
                    'onclick="setElHidden(' + el.id + ',' + (isHidden ? 0 : 1) + ')">' + toggleLbl + '</button></td>' +
                '<td><button class="btn btn-red" style="font-size:11px;padding:4px 10px;" ' +
                    'onclick="delEl(' + el.id + ',\'' + el.type + '\')">' +
                    '&#128465; Delete</button></td>' +
            '</tr>';
        }).join('');

        document.getElementById('canvas-elements-wrap').innerHTML =
            '<table><thead><tr>' +
            '<th>Type</th><th>Description</th><th>Parent</th><th>Size</th><th>Visibility</th><th>Delete</th>' +
            '</tr></thead><tbody>' + rows + '</tbody></table>';
    }

    function elDesc(el) {
        if (el.type === 'section')  return 'Section';
        if (el.type === 'image')    return 'Image';
        if (el.type === 'video')    return 'Video';
        if (el.type === 'carousel') return 'Carousel';
        if (el.type === 'marquee') {
            try { return (JSON.parse(el.manual_content || '{}').text || 'Marquee').substring(0, 60); }
            catch(e) { return 'Marquee'; }
        }
        if (el.type === 'table') {
            try {
                var td = JSON.parse(el.manual_content || '{}');
                return 'Table ' + (td.headers||[]).length + ' col × ' + (td.rows||[]).length + ' row';
            } catch(e) { return 'Table'; }
        }
        // text
        var labels = { section_header:'Section Header', item_title:'Item Title', item_title_2:'Item Title 2',
                       price:'Price', price_2:'Price 2', description:'Description' };
        var prefix = (el.block_subtype && el.block_subtype !== 'free') ? '[' + (labels[el.block_subtype]||el.block_subtype) + '] ' : '';
        var txt = (el.manual_content || '').replace(/<[^>]*>/g, '').substring(0, 60);
        return prefix + (txt || '(empty)');
    }

    function escHtml(s) {
        return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    function setElHidden(id, hidden) {
        var fd = new FormData();
        fd.append('action', 'set_element_hidden');
        fd.append('element_id', id);
        fd.append('hidden', hidden);
        fetch('api.php', { method:'POST', body:fd })
            .then(function(r) { return r.json(); })
            .then(function(res) {
                if (res.status === 'success') { loadCanvasElements(); }
                else { alert('Error: ' + (res.message || 'Unknown')); }
            });
    }

    function delEl(id, type) {
        var msg = type === 'section'
            ? 'Delete this section AND all elements inside it? This cannot be undone.'
            : 'Delete this element from the canvas? This cannot be undone.';
        if (!confirm(msg)) return;
        var fd = new FormData();
        fd.append('action', 'delete_canvas_element');
        fd.append('element_id', id);
        fetch('api.php', { method:'POST', body:fd })
            .then(function(r) { return r.json(); })
            .then(function(res) {
                if (res.status === 'success') { loadCanvasElements(); }
                else { alert('Error: ' + (res.message || 'Unknown')); }
            });
    }

    // Auto-load if Work Area is the landing tab
    if (<?= json_encode($tab) ?> === 'workarea') loadCanvasElements();

    function brandPreview() {
        var nav  = document.getElementById('brand-preview-nav');
        var bg   = document.querySelector('[name="nav_bg"]').value;
        var brd  = document.querySelector('[name="nav_border"]').value;
        var acc  = document.querySelector('[name="accent"]').value;
        var txt  = document.querySelector('[name="nav_text"]').value;
        if (nav) {
            nav.style.background = bg;
            nav.style.borderBottom = '2px solid ' + brd;
            document.getElementById('bpv-brand').style.color = txt;
            document.getElementById('bpv-btn').style.background = acc;
        }
    }

    function previewBrandLogo(input) {
        if (!input.files || !input.files[0]) return;
        var wrap = document.getElementById('brand-logo-preview');
        var img  = document.getElementById('brand-logo-img');
        var reader = new FileReader();
        reader.onload = function(e) { img.src = e.target.result; wrap.style.display = 'block'; };
        reader.readAsDataURL(input.files[0]);
    }

    function toggleEdit(id) {
        var row = document.getElementById('edit-' + id);
        row.classList.toggle('open');
    }

    function updatePreview(type) {
        var row     = document.getElementById('bs-row-' + type);
        var preview = document.getElementById('preview-' + type);
        preview.style.fontFamily  = row.querySelector('[name$="_family"]').value;
        preview.style.fontSize    = row.querySelector('[name$="_size"]').value + 'px';
        preview.style.color       = row.querySelector('[name$="_color"]').value;
        preview.style.fontWeight  = row.querySelector('[name$="_weight"]').value;
        preview.style.fontStyle   = row.querySelector('[name$="_fstyle"]').value;
        preview.style.lineHeight  = row.querySelector('[name$="_lh"]').value;
    }
</script>
</body>
</html>
