<?php
// ============================================================
// Store Branding Configuration
// Auto-generated by setup_branding.php — edit this file
// directly to update branding after initial setup.
// ============================================================
define('BRAND_LOGO',       '');          // relative path to logo, e.g. 'uploads/brand_logo.png'
define('BRAND_NAV_BG',     '#1a252f');   // builder nav background color
define('BRAND_NAV_BORDER', '#0d1b24');   // nav bottom border color
define('BRAND_ACCENT',     '#3498db');   // accent / highlight color
define('BRAND_TEXT',       '#ffffff');   // nav text color
