<?php
// ============================================================
// Store Branding Configuration
// Generated by the Admin Panel — Branding, and Site & Email.
// Edit by hand only if the Admin Panel cannot be reached; the
// next save from either form overwrites the whole file.
// ============================================================
defined('BRAND_LOGO')        || define('BRAND_LOGO',        '');
defined('BRAND_NAV_BG')      || define('BRAND_NAV_BG',      '#1a252f');
defined('BRAND_NAV_BORDER')  || define('BRAND_NAV_BORDER',  '#0d1b24');
defined('BRAND_ACCENT')      || define('BRAND_ACCENT',      '#207ab6');
defined('BRAND_TEXT')        || define('BRAND_TEXT',        '#ffffff');
defined('SITE_NAME')         || define('SITE_NAME',         'Store Display System');
defined('MAIL_FROM')         || define('MAIL_FROM',         'noreply@yourdomain.com');
defined('MAIL_FROM_NAME')    || define('MAIL_FROM_NAME',    'Display System');
